apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: devops-api-ingress
  namespace: devops-project
spec:
  rules:
    - host: devops.local
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: devops-api-service
              port:
                number: 80
