apiVersion: v1
kind: Service
metadata:
  name: devops-api-service
  namespace: devops-project
spec:
  selector:
    app: devops-api
  type: NodePort  # ou LoadBalancer si Minikube supporte
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
