name: CI/CD Pipeline

on:
  push:
    branches: [ main, feature/complete-api ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run unit tests
      run: |
        pytest -v tests/ 

    - name: Run linter (flake8)
      run: |
        flake8 app.py --max-line-length=120

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


    - name: Check Secrets
      run: |
        if [ -z "${{ secrets.DOCKER_USERNAME }}" ]; then
          echo "ERROR: DOCKER_USERNAME is not set. Check your GitHub Secrets."
          exit 1
        fi
        if [ -z "${{ secrets.DOCKER_PASSWORD }}" ]; then
          echo "ERROR: DOCKER_PASSWORD is not set."
          exit 1
        fi
    - name: Build Docker image (Local only)
      uses: docker/build-push-action@v5
      with:
        context: .
        load: true # Charge l'image dans le démon Docker local pour le scan
        tags: |
             devops-api:test
    - name: Security scan with Trivy
      uses: aquasecurity/trivy-action@0.24.0
      with:
        image-ref: devops-api:test
        format: table
        exit-code: '1' # Stoppe le pipeline si des vulnérabilités sont trouvées
        severity: CRITICAL,HIGH

    - name: Push Docker image (Only if scan passed)
      if: success()
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          diamodou1968/devops-api:latest
          diamodou1968/devops-api:${{ github.sha }}
